version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: hostelops-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: hostelops-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/hostelops
      - JWT_SECRET=supersecretkeyhostelops2025
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: hostelops-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    depends_on:
      - backend

volumes:
  mongo-data:
